### ISSUE TITLE
Create Team Github Repository

### ISSUE THREAD

**Issue by liquidmetal9015** [ZenZeppelins/HomelessAssistApp#11]
## User Story
As a Team Member, I want to have a repository so that
the team can manage our software project.

## Expected Behavior/Acceptance Criteria
- [x] There is an organization for the Zen Zeppelins
- [x] All team members have github accounts
- [x] All team members are registered to that organization
- [x] There is a repository for our main project that fulfills the requirements, including zenhub usage

**Comment by liquidmetal9015** [comment]
We still need to make sure that our last member has an account and is added to the organization. @ceremonious @cameronwalker1 @ctjosey Whoever can make that happen should do so, check the last boxes and move this into the done category.

**Comment by ctjosey** [comment]
Just got Jaleen set up
